name: Uniswap v2
event_decoder: hypersync-client
networks:
  - id: 1
    start_block: 0
    contracts:
      - name: UniswapV2Factory
        address:
          - 0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f
        handler: src/EventHandlers.ts
        events:
          - event: PairCreated(address indexed token0, address indexed token1, address pair, uint256 )
      - name: UniswapV2Pair
        address:
          - 0x3e47D7B7867BAbB558B163F92fBE352161ACcb49
        handler: src/EventHandlers.ts
        events:
          - event: Burn(address indexed sender, uint256 amount0, uint256 amount1, address indexed to)
          - event: Mint(address indexed sender, uint256 amount0, uint256 amount1)
          - event: Swap(address indexed sender, uint256 amount0In, uint256 amount1In, uint256 amount0Out, uint256 amount1Out, address indexed to)
          - event: Sync(uint112 reserve0, uint112 reserve1)
          - event: Transfer(address indexed from, address indexed to, uint256 value)
